### ISSUE TITLE
Missing TYPO3 Field, need to added by Extension

### ISSUE THREAD

**Issue by typo3max** [T3Voila/templavoilaplus#365]
Dear Maximilian.

Thanks for your request. The DB field "pages.storage_pid" is not part of TYPO3 Core anymore, and must be added by an extension (such as TemplaVoila+) themselves. Can you contact the TemplaVoila maintainer directly? I hope that helps.

All the best,
Benni.

----------------------------------------------------------
Look picture: https://ibb.co/kgZkn56

**Comment by opi99** [comment]
Hi Maximilian,

the storage_pid won't come back in TV+ v8 (in TV+ v7 we did this). Cause we do not have TemplateObjects inside database anymore.
Please describe shortly for what do you used the "storage_pid" so I can show you how to use it yet or add a new feature for you.

Greetings Alex

**Comment by typo3max** [comment]
I have a extra TemplaVoila+ Storage Folder - for this i need that - and please dont ferget the funktion for mapping in filesystem its missing too, THANK YOU!

**Comment by opi99** [comment]
In TV+ 8 we do not have Storage Folder any more. The Templates and TemplateObjects aren't inside database anymore.

If you tell me, for what you used this, then please comment and we will search for a solution.
The mapping functionality isn't easy, and yet I've no time for this point. All other functionality have a higher priority.

**Comment by typo3max** [comment]
what are doing the australopithecus afarensis?

**Comment by jpmschuler** [comment]
If you need different templates/maps only accessible for different domains/pagebranches your can use TSconfig 
`mod.web_txtemplavoilaplusLayout.filterMaps`
see https://docs.typo3.org/p/templavoilaplus/templavoilaplus/8.0/en-us/CreatingTemplateExtension/PageUserTsconfigReference/Index.html for an example

If you want to separate your templates/maps in different folders of the filesystem, you are free to arrange them however you like as you could use multiple extensions or even inside one extension multiple configurations for the places.

**Comment by opi99** [comment]
Da ich nicht weiß ob Englisch für Dich eine Sprachbarriere darstellt, wir können auch gerne auf Deutsch schreiben.

Komm doch bitte einfach in den TYPO3 Slack in den channel #templavoilaplus https://typo3.slack.com/messages/templavoilaplus
Falls Du noch keinen Slack Zugang/Einladung hast, dann einfach mit Deinem TYPO3 Account bei https://my.typo3.org/ einloggen.

**Comment by typo3max** [comment]
https://www.youtube.com/watch?v=N_aqVEcPCKU !!!!!!!
