### ISSUE TITLE
UpdateModul: Error at Typo3Lts8Update

### ISSUE THREAD

**Issue by rteitge** [T3Voila/templavoilaplus#399]
TYPO3: 10.4.30
PHP: 7.4
TV+: 8.0.5

```
[ Error ]
   Class 'TYPO3\CMS\Install\Updates\AbstractUpdate' not found

  Exception trace:
   typo3conf/ext/templavoilaplus/Classes/Updates/Typo3Lts8Update.php:27
```

**Comment by opi99** [comment]
Digging through the code ... this update module should only be available in TYPO3 v8LTS

**Comment by opi99** [comment]
As you wrote on slack you started it with

> run_as "$TYPO3_CONSOLE upgrade:run 'Tvp\TemplaVoilaPlus\Updates\Typo3Lts8Update'"

But this class isn't registered as upgrade module for TYPO3 v9LTS and newer ... so this might be an issue in TYPO3 Konsole. So closing this issue. The Backend Install Tool UpgradeWizard is working fine.
