### ISSUE TITLE
Correct Typo3 -> version 11 migration way ?

### ISSUE THREAD

**Issue by baden32** [T3Voila/templavoilaplus#401]
Hi,
A big thanks for the new TV+ version, looks realy great.

Currently, I still have Typo3 websites running version 7.6 and 8.5 with TV+ 7.3.6.

What would be the best migration way (and may be the only one) to get my websites running Typo3 11 and TV+ 8?

Should I have to install TV+ 8 on Typo3 8.7 and then upgrade Typo3 -> version 11 or should I desactivate TV+, upgrade Typo3 -> version 11 and then install &reactivate TV+ 8  (+ run the update scripts)?

Thank you in advance for your help.
Regards
Bads

**Comment by opi99** [comment]
Hi,

both ways are possible, I would tend to update TV+ on TYPO3 v8LTS and then TYPO3 if you don't use composer.
On composer installations you could upgrade TYPO3 and TV+ and then run the update scripts.

And using the Slack channel for Help https://typo3.slack.com/messages/templavoilaplus

**Comment by baden32** [comment]
Hi Alex,Thanks very much for the reply and the tips. I will try the way not using composer at the moment.Will try to connect to lack channel as well.RegardsBads
    Le jeudi 23 juin 2022, 10:39:24 UTC+2, Alexander Opitz ***@***.***> a écrit :  
 
 


Hi,

both ways are possible, I would tend to update TV+ on TYPO3 v8LTS and then TYPO3 if you don't use composer.
On composer installations you could upgrade TYPO3 and TV+ and then run the update scripts.

And using the Slack channel for Help https://typo3.slack.com/messages/templavoilaplus
