### ISSUE TITLE
PageLayoutModul: DragDrop New Elements called with wrong AJAX-URL

### ISSUE THREAD

**Issue by znmDevelopment** [T3Voila/templavoilaplus#424]
TV+ 8.1.1, TYPO3 11.5

In PageLayout.js the AJAX call on line 150 tries to get the new content record from the AJAX route 'TYPO3.settings.ajaxUrls['templavoilaplus_contentElement_insert']' which does not exist and should be 'TYPO3.settings.ajaxUrls['templavoilaplus_contentElement_create']' (Line 156)

After patching the drop of elements does work.

**Comment by opi99** [comment]
This was fixed in #411 and will be released with 8.1.2
