### ISSUE TITLE
Update configuration to TemplaVoilà! Plus 8 does not work

### ISSUE THREAD

**Issue by ralfdamm** [T3Voila/templavoilaplus#428]
No further discription for the error text "Error It seems you have deleted database tables and/or fields that are necessary for the Update Script.
Process stopped."  Our page runs with TV+ 7 without any problem. Best regards.

**Comment by jpmschuler** [comment]
Typically after deploying new extensions you probably do a command like `vendor/bin/typo3cms database:updateschema`(or run the database compare in the backend).
This command has two flavours: `safe`: only adding and changing fields and `destructive`: renaming and deleting columns and tables.

In order for the upgrade wizard to work you cannot do the destructive changes, as the upgrade wizard needs those "old columns" in order to convert it. 

So a deploy should always run all wizards before doing a destructive database update.

**Comment by opi99** [comment]
Can you explain, what did you do to upgrade your TYPO3 instance or the TV+ extension?

**Comment by ralfdamm** [comment]
Dear all, thank you very much for the comments. The problem was the complete database update prior starting the TemplaVoilà! Plus - Control Center. Now I reached step 6, but in red color. 
![Screenshot 2022-09-06 211722](https://user-images.githubusercontent.com/111906120/188720469-5f0e1d67-a517-4a34-aa56-8f6a2042051c.png). I'm very sorry bothering you with my problems..
Best regards and all  the best.

**Comment by ralfdamm** [comment]
Thank you for your comment. There is another error in the converted system, but I guess no problem of TemlaVoila! Plus 8.
The error messag is:
Oops, an error occurred!
TCA internal_type of field "field_headerimg" in table pages must be set to "db" or "folder".
Thank you again and all the best.

**Comment by opi99** [comment]
This comes from another extension in your system which adds a field to the pages table.

**Comment by ralfdamm** [comment]
Thank you very much: I do not agree. The converter builds:
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3DataStructure>
	<meta type="array">
		<langDisable>1</langDisable>
		<title>Hauptseite</title>
	</meta>
	<ROOT type="array">
		<tx_templavoilaplus type="array">
			<title>ROOT</title>
			<description>Wählen Sie das HTML-Element der Seite, das Sie als übergeordnetes Container-Element der Vorlage möchten.</description>
		</tx_templavoilaplus>
		<type>array</type>
		<el type="array">
			<field_content type="array">
				<TCEforms type="array">
					<label>Inhalt</label>
					<config type="array">
						<type>group</type>
						<internal_type>db</internal_type>
						<allowed>tt_content</allowed>
						<size>5</size>
						<maxitems>200</maxitems>
						<minitems>0</minitems>
						<multiple>1</multiple>
						<show_thumbs>1</show_thumbs>
					</config>
				</TCEforms>
			</field_content>
			_**_**<field_headerimg type="array">
				<TCEforms type="array">
					<label>Header-Bild</label>
					<config type="array">
						<type>group</type>
						<internal_type>file</internal_type>
						<allowed>gif,png,jpg,jpeg</allowed>
						<max_size>1000</max_size>
						<uploadfolder>uploads/tx_templavoila</uploadfolder>
						<show_thumbs>1</show_thumbs>
						<size>1</size>
						<maxitems>1</maxitems>
						<minitems>0</minitems>
					</config>
				</TCEforms>
			</field_headerimg>**_**_
		</el>
	</ROOT>
</T3DataStructure>
...
After removing the part /field_headerimg the page is displayed, but very simple and not like the former templates.
I regret to tell you and I'm very very sad: I must leave typo3 and TemplaVoila and got to WordPress :-( 
Best regards 
[fegtemplate.zip](https://github.com/T3Voila/templavoilaplus/files/9944687/fegtemplate.zip)
