### ISSUE TITLE
"Update configuration to TemplaVoilà! Plux 8" throws "incompatible with sql_mode=only_full_group_by" error

### ISSUE THREAD

**Issue by RetoHB** [T3Voila/templavoilaplus#433]
I am upgrading from typo3 9.5 to 11.5. My system configuration:
typo3 11.5.16
php 8.0.23

When launching the update script "Update configuration to TemplaVoilà! Plux 8" I get the following exception. Also DataStructures, Mappings and Templates shows me "Found 0 configurations". Is this normal?

An exception occurred while executing 'SELECT COUNT(`uid`), `uid`, `tx_templavoilaplus_to` FROM `tt_content` WHERE (`tx_templavoilaplus_to` <> ?) AND (`tt_content`.`deleted` = 0) GROUP BY `tx_templavoilaplus_to`' with params [""]: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mydatabase.tt_content.uid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by opi99** [comment]
You should disable the "sql_mode=only_full_group_by"

**Comment by RetoHB** [comment]
Unfortunately my hoster does refuse to remove ONLY_FULL_GROUP_BY. :-( Is there any way I can get out of this dead end?

**Comment by opi99** [comment]
Can you edit the PHP files? If yes, search for the SQL Statement inside Classes/Controller/Backend/ControlCenter/Update/TemplaVoilaPlus8Controller.php around line 467 and add "uid" to the groupBy function call.
Please report if this helps.

**Comment by RetoHB** [comment]
This seems to have fixed the update process! All worked, just at the end I get these warnings. Nothing to worry about?

![image](https://user-images.githubusercontent.com/9882700/191245829-0c4e9bf8-c24b-46d2-b881-4be1c20446a8.png)

Step 6 is greyed out, I cannot click it. Not sure if this is ok...

My userFunc line looks different than in the manual. Which one is correct?
```
page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->main_page

page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->renderPage
page.10.userFunc = Tvp\TemplaVoilaPlus\Controller\Frontend\FrontendController->renderPage
```
But now when I want to see my pages in the backend I get a ton of errors:

![image](https://user-images.githubusercontent.com/9882700/191247633-67dc4121-b1b8-427b-a51e-078191eea0e3.png)

**Comment by jpmschuler** [comment]
> step 6 is disabled

Thats only the "CleanUp" process, which isn't implemented yet and maybe won't get implemented.

> userFunc line - Which one is correct?
> 
> ```
> page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->main_page
> page.10.userFunc = Ppi\TemplaVoilaPlus\Controller\FrontendController->renderPage
> page.10.userFunc = Tvp\TemplaVoilaPlus\Controller\Frontend\FrontendController->renderPage
> ```
`Tvp\TemplaVoilaPlus\Controller\Frontend\FrontendController->renderPage` is the correct one, however the other two work automagically to increase backwards compatibility

> `Class PageRepository not found`

Indeed, the class condition is not correct, [PageRepository was still in Frontend in 9LTS](https://api.typo3.org/9.5/class_t_y_p_o3_1_1_c_m_s_1_1_frontend_1_1_page_1_1_page_repository.html). Added PR #434 as a fix

**Comment by RetoHB** [comment]
Ok, that worked! One step further. Now the next problem. In the backend I see some code of the content element at the very top:

![image](https://user-images.githubusercontent.com/9882700/191256582-daf299ae-9233-4ca1-a76d-53f07e06ef4e.png)

When I want to display the page in the frontend there is no content but an error message at the top:

![image](https://user-images.githubusercontent.com/9882700/191256748-f4533244-e8ee-4c3e-9011-1b7a80b90101.png)

**Comment by jpmschuler** [comment]
The first one is a (for me) known bug with long `tt_content.header` it will be an easy fix, could supply a PR in the next 24h.

The second one says your XPath mapping is not working, as if TVP wants to replace stuff in your template but can't find it. Look in the converted extension in `TemplateConfiguration` for that XPath string and check if it exists in the Template file. As that is a quite complex XPath even a small edit to the template file might break it. It could be helpful to add a unique `id` in the HTML template and just create a mapping to that. 
For debugging WHY and HOW the upgrade wizard didn't convert that correctly a bit more input would be necessary.

**Comment by RetoHB** [comment]
The first one does not bother me too much.

For the second one I fear I need a little more help. I can edit files on the server but I need to know where I have to do what... My knowledge of typo3 code is not very high unfortunately...
Please let me know what more info I need to post to get this resolved.

**Comment by jpmschuler** [comment]
the actual TVP TemplateConfiguration would be necessary (the file with all the xpath strings like the one that is on top of the screenshot) and the HTML-Template that is mentioned in that TemplateConfiguration. As this is a page template probably something like:

- EXT:yourext/Resources/Private/TVP/TemplateConfiguration/Pages/index.*
- EXT:yourext/Resources/Private/TVP/Template/index.*

If you don't want to disclose this publicly we could switch the debugging to Slack
How to access Slack: https://typo3.org/community/meet/chat-slack
TVP-channel: [#templavoilaplus](https://typo3.slack.com/archives/C4HCAH659 )

**Comment by RetoHB** [comment]
Not being familiar with Slack. I have now connected my Slack to typo3. Do I need to add you now somehow?

![image](https://user-images.githubusercontent.com/9882700/191279344-14bb1179-13d8-4599-91a1-9034c279a7ea.png)

**Comment by opi99** [comment]
Fine that adding the code to UpdateScript helped you ... can you make a PullRequest to this repository so I can merge this for other users?

To the template issue which is left open, I see, that you your "old" non XPath compatible selector is a bit hard, I will try to understand it and try to fix the migration for that situation, but this may need some time.

**Comment by opi99** [comment]
The index.zip contains not the template with issues, the template in question is the "subtemplate" (as also seen in first screenshot).
The index.html and index.yaml.tvp seam to work correctly.

**Comment by RetoHB** [comment]
Here is my subtemplate file: 
[subtemplates.zip](https://github.com/T3Voila/templavoilaplus/files/9622690/subtemplates.zip)

**Comment by opi99** [comment]
Thanks for your patch, so congratulation for your first code line in TV+ ;-)

The zip file only contains the template, but not the resulting mapping configuration, which I need to check, whats wrong.

**Comment by RetoHB** [comment]
Sorry for the stupid question: where can I get the mapping configuration?

**Comment by jpmschuler** [comment]
In your migrated extension results are all below 
`EXT:yourext/Resources/Private/TVP/`
sorted in meaningful named folders:
```
EXT:yourext/Resources/Private/TVP/MappingConfiguration/Pages/*
EXT:yourext/Resources/Private/TVP/TemplateConfiguration/Pages/*
EXT:yourext/Resources/Private/TVP/Template/*
```

**Comment by RetoHB** [comment]
I hope this is it: 
[MappingConfiguration.zip](https://github.com/T3Voila/templavoilaplus/files/9624154/MappingConfiguration.zip)

**Comment by opi99** [comment]
Ahh, the ones from the EXT:yourext/Resources/Private/TVP/TemplateConfiguration/ directory ;-)

Or best put the full EXT:yourext/Resources/Private/TVP/ into the zip file

**Comment by RetoHB** [comment]
Did you see the new zip file above?

**Comment by RetoHB** [comment]
[TVP.zip](https://github.com/T3Voila/templavoilaplus/files/9631398/TVP.zip)

**Comment by opi99** [comment]
Ok, I see what is wrong but at the moment it looks like it is already wrong before converting?

The 50/50 Subtemplate contains same mapping as the 38/62 subtemplate. The 62/38 subtemplate contains the 50/50 mapping data ... so something was already broken before and so I don't know, what should be what?

It seams someone added the Box80 (or Box90) before the other boxes inside the subtemplate.html which maybe got mapped partielly.

in subtemplate2.tvp.yaml the mapping path is correctly transformed but it should have been

`//div[@class="ym-wrapper"][2]` for the field_left and field_right (note the 2 and not a 1), same gose to subtemplate3.tvp.yaml but there it may had a 3 instead of 1.
So transformation didn't go wrong, but the mapping was previously wrong (and eventually hidden by the template caching in old TemplaVoilà!)

So please adjust the xpath in your files inside TVP/TemplateConfiguration/Fces/subtemplates[2-4].tvp.yaml files. You may also need to rename the template name or the boxes which are selected depending on your system data.

**Comment by RetoHB** [comment]
Thank you! It seems I was able to fix this, the Frontend rendering looks ok now.
But I think there is still a problem in the backend. Or I do not understand how the new TVP works...
I can drag content templates into a new page but I cannot add any content...

![image](https://user-images.githubusercontent.com/9882700/192032762-2bb35323-2bb4-43fb-9970-45a46b6aebf0.png)

**Comment by opi99** [comment]
For the Backend issue, you may try the actual master (or wait for 8.1.2) ... for the frontend thing which happened, todays morning I had an 💡  ... it may be a different handling between TV and TV+ 8 about the first outer mapping like in your configuration. Need to check this out but it might be I don't want to change this. Would leave that untouched IMHO, as it was fixable by changing your selectors.

So, at the moment I would only handle your BE issue. Ok?

**Comment by RetoHB** [comment]
That's ok for me. So for the BE issue you have an idea for the next release? What is the time frame for this? If possible I would like to avoid messing around manually...

**Comment by opi99** [comment]
There is a fix in latest source, which you could try if this helps.
Next release, I thought I've time last Friday, but didn't happen, maybe this week.

**Comment by RetoHB** [comment]
So if you do not find the time to release the next version. How can I try it manually?

**Comment by jpmschuler** [comment]
> So if you do not find the time to release the next version. How can I try it manually?

If you have a legacy (non-composer) install you can [download the main branch as a zip](https://github.com/T3Voila/templavoilaplus/archive/refs/heads/main.zip) and replace the local extension.
If you have a composer install you can require `dev-main` as a version to get the latest code, instead of something like `^8.1`

**Comment by opi99** [comment]
For the open issue from this long bugreport, the defective XPath, I opened a new issue #460 to solve this.
So for now, I will close this issue, as all other parts should be fixed for now. If not, feel free to open another issue report.
