### ISSUE TITLE
Edit tt_content field with linkbrowser (like tt_content.header_link or tt_content.image.link) broken

### ISSUE THREAD

**Issue by jpmschuler** [T3Voila/templavoilaplus#451]
Steps to reproduce:

1. Open TVP page module
2. Navigate to page which has content elements
3. Edit content element
4. Go to field `header_link` and use the linkbrowser to select e.g. a page or something, or update the css class of an existing link etc.
=> ERROR: The click on the new page will close the linkbrowser, but the field header_link won't get updated

This is bound to TVP, as doing the same in LIST module works. Tested for 10LTS and 11LTS.

Couldn't find anything in browser console, browser network tab or TYPO3 logs, but seems the return value / event listener is not bound correctly.

**Comment by jpmschuler** [comment]
same goes for linking images as part of a `textpic` or `textmedia` as there the same linkbrowser is used.

**Comment by jpmschuler** [comment]
The modal iframe URL is fine, copying that to a new tab and opening it without the page module around it works, too.

**Comment by opi99** [comment]
Hmmm, there was a fix in #299 for this issue, but I may never test it with the link wizard

**Comment by opi99** [comment]
The issue is the file typo3/sysext/backend/Resources/Public/JavaScript/FormEngineLinkBrowserAdapter.js

In function FormEngineLinkBrowserAdapter.checkReference it calls FormEngineLinkBrowserAdapter.getParent(); which returns (as it seams) the TV+ frame (as it haves an open modal) instead of the FormFramework iframe which opened that modal.

That is very stupid, and unlike on RecordList (like FAL) do not use message events.

From my point of view, this is stupid, broken and unfixable but I've no experiences in JavaScript.

**Comment by jpmschuler** [comment]
So after 3 month of hiatus because I had no access to my CI/CD I got the solution for a core patch as https://github.com/jpmschuler/backend/pull/1.patch 
Which can be easily installed to a 11LTS via `composer-patches`.

I know currently no way of how to supply this automatically via just installing TVP, but will look into it.

**Comment by jpmschuler** [comment]
We could override the core controller `Classes/Controller/LinkBrowserController.php` using `AjaxRoutes.php` extend it, override `initDocumentTemplate()` and load a different RequireJSModule (Ours, with the 4 extra lines).

That would need a lot of LTS-if/else. Out of scope currently for me.

Two other approaches:
- ask in coredev if they would consider patching EXT:backend
- find a way to override RequireJS namespaces

**Comment by opi99** [comment]
Needed to change `window.parent.document.list_frame` to `window.parent.frames.list_frame` or do we need to implement both variants for browser compatibility?

**Comment by jpmschuler** [comment]
¯\_(ツ)_/¯ didn't test cross browser yet. didn't expect such base JS to be different.

Yours seems plausible. will test it in the next week

**Comment by jpmschuler** [comment]
I confirm that this is fixed via 0b78cac
