### ISSUE TITLE
Undefined constant 'TYPO3\CMS\Frontend\Page\PageRepository'

### ISSUE THREAD

**Issue by RetoHB** [T3Voila/templavoilaplus#463]
I think I found a new issue on one of my other websites, still running typo3 9.5

![image](https://user-images.githubusercontent.com/9882700/197605638-3ecebaf8-a2dd-4397-a006-f3f0e4781a97.png)

TVP 8.1.2. Not sure how to fix this...

**Comment by opi99** [comment]
Oh, ok ... can you add '::class' please? So the line reads:

`$pageRepositoryClass = \TYPO3\CMS\Frontend\Page\PageRepository::class;`

And report back? (Or do a Pull request with this change if all is fine)

**Comment by jpmschuler** [comment]
don't have a system with <10 to test up and running to test, but this proposed fix is correct.
However I deem https://github.com/T3Voila/templavoilaplus/pull/464/commits/257a5a94adfa79bab363f85a679b6520c446ac82 better as this uses the TVP adapter for PageRepository centralising this case condition.

**Comment by RetoHB** [comment]
The above fix by adding ::class works for me. So I am not sure which solution you want to implement...
