### ISSUE TITLE
11LTS: improve page module CSS as it breaks on very small screens

### ISSUE THREAD

**Issue by jpmschuler** [T3Voila/templavoilaplus#465]
With quite long page names they break, thus make the top menu bigger, thus that gets over the sidebar of TVP covering buttons.
Solution:  no fixed top position, but relative one.

Will supply PR as soon as time.
![example](https://user-images.githubusercontent.com/12411176/197764284-995d5bf9-9784-476f-a12a-3ea333ac47ac.png)

**Comment by jpmschuler** [comment]
For reference: the moving top has something to do with the "old" BackendTemplates used to retain <=10 compatibility, which are deprecated in 11 and removed in 12.

Probably will steal some css from there which eases this, but need to fire up some custom ddev machines for tests as all my primary systems are now 11LTS.

**Comment by jpmschuler** [comment]
for reference: fixed that in #468 with the approach of 11LTS to enforce that big breaking line to be one line only (using `word-wrap`

**Comment by opi99** [comment]
So this can be closed?

**Comment by jpmschuler** [comment]
yes, at time of my comment #468 was not merged!

**Comment by opi99** [comment]
:)
