### ISSUE TITLE
TV+ with workspace not working

### ISSUE THREAD

**Issue by Qrecki** [T3Voila/templavoilaplus#487]
I try, to run templavoila+ on typo3 with workspace. When i click on workspaces i recive an error: **Unable to generate a URL for the named route "web_txtemplavoilaplusLayout" because this route was not found.**

Also when i try add new content when i work in workspace "add" content buton is disabled.

I try on typo3: 11.5.21, 11.5.22 and 11.5.23 also try TV+ 8.0.5 and 8.1.2

**Comment by opi99** [comment]
Thanks for reporting, will check, as I do not own/manage a TYPO3 version with workspaces anymore, I didn't checked it yet.

**Comment by opi99** [comment]
Fixed issue with named route. The other issue didn't show up on my system, if it still exists then please open a new issue report to track this down.
