### ISSUE TITLE
No value reported in the input field (inputLink)

### ISSUE THREAD

**Issue by gregordonsky** [T3Voila/templavoilaplus#502]
### Prerequisites:
1. typo3 10.4.36
2. Templavoilaplus 8.1.3

### Description:
If in an FCE i have this XML-configuration for an input field:

```xml
...
<field_linkreadmore type="array">
  <TCEforms type="array">
    <label>Link destinazione</label>
    <config type="array">
      <type>input</type>
      <size>15</size>
      <max>256</max>
      <checkbox></checkbox>
      <eval>trim</eval>
      <wizards type="array">
        <_PADDING type="integer">2</_PADDING>
      </wizards>
      <renderType>inputLink</renderType>
      <fieldControl type="array">
      <linkPopup type="array">
        <options type="array">
          <title>Link</title>
          <windowOpenParameters>height=300,width=500,status=0,menubar=0,scrollbars=1</windowOpenParameters>
        </options>
      </linkPopup>
      </fieldControl>
    </config>
  </TCEforms>
</field_linkreadmore>
```

When i select a page or set a link in the link browser popup, the link is not reported in the field:

Click Here:
![image](https://user-images.githubusercontent.com/48908421/230426223-f7efb422-5606-4f2e-8bef-ebc37aaaf5a5.png)

Next step ( in this case i inserted an external url, but it does not work also if i select a page ):
![image](https://user-images.githubusercontent.com/48908421/230426620-5e1c0ea4-4bbe-4846-89f6-a8af164b5b29.png)

No value is in the field:
![image](https://user-images.githubusercontent.com/48908421/230426776-3d917d09-3c6e-43a9-9655-e220011f02a8.png)

**Comment by jpmschuler** [comment]
relates to #451, 0b78cac and ddee482 which was released as 8.1.3.
As you use 8.1.3, this seems to be similar, but needing additional treatment.

**Comment by gregordonsky** [comment]
ok @jpmschuler , thank you for pointing me in the right direction.

I see that in my typo3 installation FormEngineLinkBrowserAdapter.js from templavoilaplus is not loaded.
So all the link wizards don't work, even the fields reported in the issue #451 .
I wonder if it is related to the typo3 version, because it seems to me that TYPO3\CMS\Core\Page\JavaScriptModuleInstruction
it is not present in typo3 v.10 sources

**Comment by opi99** [comment]
Ah, so we missed TYPO3 v10 LTS ... damn :-(
