### ISSUE TITLE
LinkBrowser and canonical link

### ISSUE THREAD

**Issue by gregordonsky** [T3Voila/templavoilaplus#509]
### Prerequisites:
1. typo3 10.4.36 / Typo3 11.5.26
2. Templavoilaplus 8.1.3

Related to #451 and #502 

Unfortunately with the latest version and the bugfix for the link browser, the canonical link field doesn't work in all cases.

---

Typo3 11:
![image](https://github.com/T3Voila/templavoilaplus/assets/48908421/3e8e2b12-0e4e-4252-8310-d0cc89a30b08)

Next  step:
![image](https://github.com/T3Voila/templavoilaplus/assets/48908421/7db70689-4d32-4ade-bfeb-5dc299fd51d0)

Then when you select an item in the linkbrowser window there is no value in the input.

----
Typo3 10:
![image](https://github.com/T3Voila/templavoilaplus/assets/48908421/66950d28-c4b0-43a9-82e5-b522ef3f1758)

Next  step:
![image](https://github.com/T3Voila/templavoilaplus/assets/48908421/e24110ea-35c0-4942-b7cc-23e5d1bba37d)

Then when you select an item in the linkbrowser window there is no value in the input.

**Comment by opi99** [comment]
Fixed with merge of #542
