### ISSUE TITLE
Re-ordering tt_content elements in list module results in 503

### ISSUE THREAD

**Issue by jpmschuler** [T3Voila/templavoilaplus#512]
Steps to reproduce:

- Have a page with more than one tt_content element. 
- Go to list module, table tt_content.
- click on the chevron-up for the second tt_content element to move it's position.

Expected output:

- the second element is now first in list module
- (probably) if both are in the same TVP field (historically colpos): reorder them in TVP flex field and thus in output, too.

Current output:
Exception 503: `Call to undefined method Tvp\TemplaVoilaPlus\Service\ApiService::moveElement_setElementReferences()`

**Comment by jpmschuler** [comment]
That was a simple fix in e516fd73, however this works for most cases, but some now throw a different exception, will create PR as soon as that is resolved, too.

**Comment by jpmschuler** [comment]
I dug deeper into it. Could resolve all exceptions and the result was that "some" movements had effect on TVP ordering but some didn't. Especially the [maxPosition check](https://github.com/T3Voila/templavoilaplus/blob/fb9ff0c865b34299540b803ef3c7726b6bdd08c2/Classes/Service/ProcessingService.php#L911-L918) seems off as I got a simple box with two elements moving 0 down (thus behind 1) which resulted in a new position "2" while maxPosition was "1" aborting the move. However I didn't remove that check because that part has a lot of legacy stuff with unclear comments.

So I rather think catching all the exceptions and trying the best is the better solution for now.

**Comment by opi99** [comment]
Yes, the maxPosition check is a bit strange, I also debugged there around. 

Fix for master only or master and 8.1.x branch?
