### ISSUE TITLE
Unable to edit/update Data Structures, Mappings or Templates after upgrade to Typo3 v11

### ISSUE THREAD

**Issue by baden32** [T3Voila/templavoilaplus#515]
I just upgraded all components of my website to Typo3 v11 and the whole display/layout is fine.
TVP+ has been updated to version 8.1.3 and I can see the Data Structures, Mappings or Templates definitons.

Unfortunately, if I make a change in one of the template file, I cannot find how to edit the template in TVP+ settings, all the options, except trash icon for Data Structures are not active (see attached image).

Am I doing something wrong here or do I need to add specific config/setup in order to get be able to edit these definitions?

Thank you in advance form your help.
Regards,
Joël

![tvp-plus-template-list](https://github.com/T3Voila/templavoilaplus/assets/3597655/d78b5ebd-e060-4f5f-a452-b63d42260134)
![tvp-plus-ds-list](https://github.com/T3Voila/templavoilaplus/assets/3597655/b56cce2d-184c-4043-a350-994ed21de58b)

**Comment by jpmschuler** [comment]
Currently no backend editing of DataStructure and Mappings is possible. However after the upgrade wizard ran all the files are generated in an extension and you can edit that extension using the normal means (e.g. download it, put it in a git repo and use your IDE.
To get an idea how they look like, the files from the example extension are at https://github.com/extrameile/em_tvplus_theme_demo/tree/master/Resources/Private

**Comment by baden32** [comment]
Hi Peter,
Thanks for your reply. 
Effectively the different files are in the "extension" directories and I can change/adapt them manually.
Issue can be closed.
Regards,
Bads

**Comment by opi99** [comment]
Hi,

thanks for answering.
