### ISSUE TITLE
Cannot cast an array to string in Templavoilaplus 8.1

### ISSUE THREAD

**Issue by fhamelin** [T3Voila/templavoilaplus#550]
This bug was fixed in 12.0.0 by commit 577f1c3 but is still present in 8.1.4. 

It looks like the opening and closing f:debug tags are evaluated as strings and cast to strings along with the node.datastructure.sheets array in TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\AbstractNode::evaluateChildNodes. It causes the error "Cannot cast an array to string" once after the cache is cleared then everything works fine afterwards.

**Comment by opi99** [comment]
Is in 8.2.x fixed, backportet into 8.1.x branch.
