### ISSUE TITLE
Copy of content element generates a reference on paste in to another page

### ISSUE THREAD

**Issue by derBoogie** [T3Voila/templavoilaplus#556]
When copying a content element, a reference is created instead of a copy, when it is pasted on another page.

Also, the Button "make a local copy" doesn't work.

TYPO3 11.5.33 and TVP 8.1.4

**Comment by opi99** [comment]
Hi, I can't verify this issue (on latest 8.2.0 branch). I used the Drag'n'Drop method, how did you copy the element?

**Comment by derBoogie** [comment]
> Hi, I can't verify this issue (on latest 8.2.0 branch). I used the Drag'n'Drop method, how did you copy the element?

Hi @opi99,
I copied the content elements with the copy-button into the clipboard and pasted it with the paste in-button into another page.

**Comment by opi99** [comment]
You mean the "paste after" in the submenu? (There is no "paste in" button) and (as I see) this do not paste anything. :-/
Can you make a screenshot? Maybe something else do not work ;)

**Comment by derBoogie** [comment]
Hi @opi99,
Please excuse me, false alarm. Copy and paste works as intended. There is no such bug. I did not notice the options "copy" / "move", "refereciate", in the clipboard dialog (Screenshot).
![TVP+Clipboard](https://github.com/T3Voila/templavoilaplus/assets/1611217/e21de6e0-e132-47e8-bcae-0cc1d3dea7e3)

**Comment by opi99** [comment]
Ahhh, ok, thx for feedback, so I can close this issue?

**Comment by derBoogie** [comment]
Yes, you can close =)
