### ISSUE TITLE
Why you can't map with TemplaVoila Plus for TYPO3 11 & 12

### ISSUE THREAD

**Issue by typo3max** [T3Voila/templavoilaplus#558]
Thank you for the Extension, but why?

**Comment by opi99** [comment]
Beginning with TV+ 8 we completely changed the handling also some parts of the code were not maintainable in its state and there was no time yet. So the mapping part was removed.

There will be (if someone code it) the possibility to create the DataStructures. But if there will be time to add the XPath mapping? I don't know, cause the XPath Templates are a bit out of usage and most users will switch to fluid templates inside TV+.
