### ISSUE TITLE
Drag and Drop in page module broken for safari in 11LTS/8.2x and 12LTS/main

### ISSUE THREAD

**Issue by jpmschuler** [T3Voila/templavoilaplus#562]
Somewhere around fixing https://github.com/T3Voila/templavoilaplus/issues/560 my Safari stopped working Drag and Drop in page module. Like drag around, add new elements, add elements from trashbin. All those work fine in Chrome, but in Safari they are stuck in "yellow state" (i.e. they are dropped, but the AJAX call is not fired or doesn't get a response).
`TypeError: null is not an object (evaluating 'evt.target.dataset') in OnAdd PageLayout.js:306` for 12LTS and line `:273` for 11LTS

**Comment by opi99** [comment]
The diff between 1.15.0 and 1.15.2 doesn't show something wired, 
So 2 questions:
* Does this also happen to move an element into trash?
* Did you try to go back to 1.15.1 or 1.15.0 but with the changes in TV+?

**Comment by jpmschuler** [comment]
> * Did you try to go back to 1.15.1 or 1.15.0 but with the changes in TV+?

Didn't have time for a code-based debug yet.

> * Does this also happen to move an element into trash?

- moving to clipboard works
- moving to trash works
- moving from new/wizard to page doesn't work
- moving from clipboard to page doesn't work
- moving from trash to page doesn't work

**Comment by opi99** [comment]
Ok, so the bug could
* is older and gets only visible by the changed thresholds
* the new child rec calculation in SortableJS leads to an hidden bug in SortableJS/Safari
