### ISSUE TITLE
 multi language issue 

### ISSUE THREAD

**Issue by omartypo3** [T3Voila/templavoilaplus#569]
Hi,
i'm working on multi language typo3 site (12.4.13)  with TemplaVoilà! Plus (12.0.0)
when i change the language i got this error 
![image](https://github.com/T3Voila/templavoilaplus/assets/24434647/15430104-2857-4d3d-b8c7-7ba172c54879)
but in the default it's working fine

**Comment by opi99** [comment]
Hi,

where do you get it and what multi language system do you use (TYPO3 Core or the TV+ one?).
Is this a migrated site or a new one?

Greetings

**Comment by omartypo3** [comment]
Hi, 
i use TYPO3 Core for multi language and i migrated site from v11 to 12
Greetings

**Comment by opi99** [comment]
I don't think it comes from the YAML file.

What did you do, to get the error? Is it in frontend or backend? Do you have a stacktrace for me? (Maybe inside the typo3 logfile.)

**Comment by omartypo3** [comment]
it is in backend 
this is the log file 
[error.txt](https://github.com/T3Voila/templavoilaplus/files/15259777/error.txt)
