### ISSUE TITLE
RouteNotFoundException in backend after update to TYPO3 v12

### ISSUE THREAD

**Issue by derBoogie** [T3Voila/templavoilaplus#572]
After updating from TYPO3 v11 to TYPO3 12.4.16, I get the following exception in the backend when I edit a Powermail plugin:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476050190: Unable to generate a URL for the named route "web_layout" because this route was not found. | TYPO3\CMS\Backend\Routing\Exception\RouteNotFoundException thrown in file /html/typo3-update/typo3_src-12.4.16/typo3/sysext/backend/Classes/Routing/UriBuilder.php in line 146. Requested URL: https://mydomain.tld/typo3/record/edit?token=--AnonymizedToken--&edit%5Btt_content%5D%5B6373%5D=edit&returnUrl=%2Ftypo3%2Ftemplavoilaplus%2Fmodalhelper%2Fclose%3Ftoken%3D--AnonymizedToken--

![grafik](https://github.com/T3Voila/templavoilaplus/assets/1611217/2bdda7c0-9224-4183-a231-68a9c6d059e6)

The XHR-request is: https://mydomain.tld/typo3/ajax/templavoilaplus/record/editform?token=83a87f33005f268a61847707d0f20dae67445158&table=tt_content&uid=3044

The Powermail Plugin should look like this in the backend:
![grafik](https://github.com/T3Voila/templavoilaplus/assets/1611217/86312782-d1f9-43dd-8c50-7372da2d4fb6)

But here something is missing:
![grafik](https://github.com/T3Voila/templavoilaplus/assets/1611217/5d018e9e-ed05-42b8-8592-337869ac713e)

The powermail form is displayed correctly in the frontend.

I put a logger inside the /Be/UriViewHelper.php and figured out, that the UriViewHelper ist only called by editing a Powermail plugin. All other content elements, including other plugins do not call the UriViewHelper.

Powermail version: 12.3.5
TemplaVoilà! Plus version: 12.0.0

**Comment by opi99** [comment]
So, part one is solved, no error anymore. But PlugIn Preview output seams broken.
